[project]
name = 'Blockchain-Enabled-Accessibility-Compliance-Tracking'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.certification]
path = 'contracts/certification.clar'
clarity_version = 2
epoch = 2.5

[contracts.facility-assessment]
path = 'contracts/facility-assessment.clar'
clarity_version = 2
epoch = 2.5

[contracts.improvement-tracking]
path = 'contracts/improvement-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.user-feedback]
path = 'contracts/user-feedback.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
